# deployment
version: '3'

networks:
  back-tier:

services:
  database:
    build: 
      context: ./database
      dockerfile: ./Dockerfile
    container_name: database
    networks:
      - back-tier
    ports:
      - "5432:5432"
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  website:
    build: 
      context: ./website
      dockerfile: ./Dockerfile.deploy
    # image: thomasr96/vancouverspecialrecognition_website
    networks:
      - back-tier
    ports:
      - "80:8080"
    environment: 
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
      # jdbc:postgresql://host:port/database
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/${POSTGRES_DB}
      - SPRING_DATASOURCE_USERNAME=${POSTGRES_USER}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRES_PASSWORD}
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - database
      - yolo
  yolo:
    build: ./yolo_api
    # image: thomasr96/vancouverspecialrecognition_yolo
    networks:
      - back-tier
    ports:
      - "5000:5000"
    # depends_on:
    #   - database