version: '3'

networks:
  back-tier:

services:
  # database:
  #   build: ./Database
  #   networks:
  #     - back-tier
  #   ports:
  #     - "27017:27017"
  website:
    # build: ./website
    image: thomasr96/vancouverspecialrecognition_website
    networks:
      - back-tier
    ports:
      - "8080:8080"
    # depends_on:
    #   - database
  yolo:
    # build: ./yolo_api
    image: thomasr96/vancouverspecialrecognition_yolo
    networks:
      - back-tier
    ports:
      - "5000:5000"
    # depends_on:
    #   - database