# development
version: '3'

networks:
  back-tier:

services:
  database:
    build: 
      context: ./database
      dockerfile: ./Dockerfile
    networks:
      - back-tier
    ports:
      - "3000:3000"
    environment: 
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
  website:
    build: 
      context: ./website
      dockerfile: ./Dockerfile.dev
    # image: thomasr96/vancouverspecialrecognition_website
    networks:
      - back-tier
    ports:
      - "80:8080"
    volumes:
      - ./website/src:/workspace/app/src
    environment: 
      - GOOGLE_MAPS_API_KEY=${GOOGLE_MAPS_API_KEY}
    depends_on:
      - database
      - yolo
  yolo:
    build: ./yolo_api
    # image: thomasr96/vancouverspecialrecognition_yolo
    networks:
      - back-tier
    ports:
      - "5000:5000"
    volumes:
      - ./yolo_api:/app
    # depends_on:
    #   - database